import Layout from "../components/layout";
import {DATABASE_ID, TOKEN} from "../config";
import Head from "next/head";

export async function getStaticProps() {
  console.log(DATABASE_ID, TOKEN);
  const options = {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Notion-Version": "2022-06-28",
      "content-type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({page_size: 100}),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );
  const result = await res.json();
  console.log(result);
  return {
    props: {},
  };
}

export default function Projects() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>프로젝트</h1>
    </Layout>
  );
}
