import Layout from "../components/layout";
import { DATABASE_ID, TOKEN } from "../config";
import Head from "next/head";
import ProjectItem from "../components/projects/project-item";

export async function getStaticProps() {
  console.log(DATABASE_ID, TOKEN);
  const options = {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Notion-Version": "2022-06-28",
      "content-type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      sorts: [
        {
          //property 소팅의 기준
          property: "Name",
          direction: "ascending",
        },
      ],
      page_size: 100,
    }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );
  const projects = await res.json();

  return {
    props: { projects },
  };
}

//className="grid grid-cols-1 md:grid-cols-2 gap-8 sm:w-full"
//코드설명: md:에 걸렸을 때 grid의 컬럼을 2개로 요소 사이의 갭은 8이고 가장 작아졌을 때 width값은 full로
export default function Projects({ projects }) {
  return (
    <Layout>
      <div className="flex flex-col items-center justify-center px-6 mb-10">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="text-4xl font-bold sm:text-6xl">
          총 프로젝트 :
          <span className="pl-4 text-blue-500">{projects?.results.length}</span>
        </h1>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 m-6 py-10">
          {projects &&
            projects.results.map((aProject) => (
              <ProjectItem key={aProject.id} data={aProject} />
            ))}
        </div>
      </div>
    </Layout>
  );
}
